# Generated by Django 2.0.6 on 2018-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='用例编号')),
                ('name', models.CharField(max_length=60, verbose_name='用例名称')),
            ],
            options={
                'verbose_name_plural': '测试用例管理',
                'verbose_name': '测试用例',
            },
        ),
    ]
