# Generated by Django 2.0.6 on 2018-06-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.SmallIntegerField(choices=[(1, '输入'), (2, '点击'), (3, '匹配')], default=0, verbose_name='类型')),
                ('xpath', models.CharField(blank=True, help_text='用于找到对象', max_length=100, null=True, verbose_name='XPATH')),
                ('step_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='提交的值')),
                ('sort_order', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name': '用例步骤',
                'verbose_name_plural': '用例步骤管理',
            },
        ),
        migrations.AddField(
            model_name='usercase',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用例网址'),
        ),
        migrations.AddField(
            model_name='usercasestep',
            name='user_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.UserCase'),
        ),
    ]
