# Generated by Django 2.0.6 on 2018-06-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180627_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercasestep',
            name='pause_seconds',
            field=models.PositiveSmallIntegerField(default=0, help_text='单位秒', verbose_name='暂停时间'),
        ),
        migrations.AlterField(
            model_name='usercasestep',
            name='sort_order',
            field=models.IntegerField(default=100, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='usercasestep',
            name='user_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='app.UserCase'),
        ),
    ]
