# Generated by Django 2.0.6 on 2018-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180628_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercasestep',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='备注名'),
        ),
    ]
