# Generated by Django 2.0.6 on 2018-06-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usercasestep_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercasestep',
            old_name='sort_order',
            new_name='order',
        ),
    ]
