# Generated by Django 2.0.6 on 2018-06-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180628_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercasestep',
            options={'ordering': ['order'], 'verbose_name': '用例步骤', 'verbose_name_plural': '用例步骤管理'},
        ),
        migrations.AlterField(
            model_name='usercasestep',
            name='order',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='排序'),
        ),
    ]
